// apps/frontend-next/components/Signup.tsx
import { useSignUpMutation } from '@api/generated'
import {
   Modal,
   ModalBody,
   ModalCloseButton,
   ModalContent,
   ModalFooter,
   ModalHeader,
   ModalOverlay,
   useDisclosure,
} from '@chakra-ui/react'
import { Formik, ErrorMessage } from 'formik'
import Link from 'next/link'
import { useRouter } from 'next/router'
import toast from 'react-hot-toast'
import * as Yup from 'yup'
import Button from './utils/Button'
import DisplayError from './utils/DisplayError'
import { FieldStyles, FormStyles, LabelStyles } from './utils/Form'

const SignupSchema = Yup.object().shape({
   name: Yup.string()
      .min(2, 'От двух символов')
      .max(50, 'Не больше 50 символов')
      .required('Обязательно'),
   lastName: Yup.string()
      .min(2, 'От двух символов')
      .max(50, 'Не больше 50 символов')
      .required('Обязательно'),
   email: Yup.string().email('Неверный email').required('Обязательно'),
   password: Yup.string()
      .min(2, 'От двух символов')
      .max(50, 'Не больше 50 символов')
      .required('Обязательно'),
})

const SignUp = () => {
   const [signUp, { isLoading, error, data }] = useSignUpMutation()

   const { isOpen, onOpen, onClose } = useDisclosure()
   const router = useRouter()

   return (
      <div className="max-w-md mx-auto my-6 bg-slate-200 p-4 lg:p-6 rounded-lg shadow-md">
         <h1 className="underline decoration-blue-500">Регистрация</h1>
         <Formik
            initialValues={{
               name: '',
               lastName: '',
               email: '',
               password: '',
            }}
            validateOnBlur={false}
            validateOnChange={false}
            validationSchema={SignupSchema}
            onSubmit={async (values, actions) => {
               signUp(values)
                  .unwrap()
                  .then(() => {
                     onOpen()
                     actions.resetForm()
                  })
                  .catch(err => {
                     toast.error('Ошибка')
                  })
            }}
         >
            {() => (
               <FormStyles className="mt-3">
                  <fieldset
                     disabled={isLoading}
                     style={isLoading ? { opacity: '0.5' } : {}}
                  >
                     <LabelStyles>
                        Имя:
                        <FieldStyles name="name" />
                        <ErrorMessage
                           name="name"
                           render={msg => <DisplayError error={msg} />}
                        />
                     </LabelStyles>
                     <LabelStyles>
                        Фамилия:
                        <FieldStyles name="lastName" />
                        <ErrorMessage
                           name="lastName"
                           render={msg => <DisplayError error={msg} />}
                        />
                     </LabelStyles>
                     <LabelStyles>
                        Почта:
                        <FieldStyles name="email" type="email" />
                        <ErrorMessage
                           name="email"
                           render={msg => <DisplayError error={msg} />}
                        />
                     </LabelStyles>
                     <LabelStyles>
                        Пароль:
                        <FieldStyles name="password" type="password" />
                        <ErrorMessage
                           name="password"
                           render={msg => <DisplayError error={msg} />}
                        />
                     </LabelStyles>
                     {error && <DisplayError error={error} />}
                     <Button type="submit" className="mt-3 w-full">
                        Зарегистрироваться
                     </Button>
                  </fieldset>
               </FormStyles>
            )}
         </Formik>

         <p className="text-center underline pt-3">
            <Link href="/login">
               <a>Войти</a>
            </Link>
         </p>

         <Modal onClose={onClose} isOpen={isOpen} isCentered>
            <ModalOverlay />
            <ModalContent>
               <ModalHeader>Регистрация</ModalHeader>
               <ModalCloseButton />
               <ModalBody>
                  <p>
                     Для подтверждения аккаунта перейдите по ссылке,
                     отправленной на почту
                  </p>
               </ModalBody>
               <ModalFooter>
                  <Button
                     onClick={() => {
                        router.push('/login')
                        onClose()
                     }}
                  >
                     Ок
                  </Button>
               </ModalFooter>
            </ModalContent>
         </Modal>
      </div>
   )
}

export default SignUp

// apps/svelte-kit/src/components/Auth/Signup.svelte
<script lang="ts">
   import {
      SignUpDocument,
      type SignUpMutation,
      type SignUpMutationVariables
   } from '$api/generated'
   import { goto } from '$app/navigation'
   import { validateForm } from '$lib/utils'
   import { mutation, operationStore } from '@urql/svelte'
   import * as yup from 'yup'

   const schema = yup.object().shape({
      name: yup.string().required('Обязательно'),
      lastName: yup.string().required('Обязательно'),
      email: yup.string().required('Обязательно').email('Неверный email'),
      password: yup.string().required('Обязательно')
   })

   const signup = mutation(operationStore<SignUpMutation, SignUpMutationVariables>(SignUpDocument))

   let name: string = ''
   let lastName: string = ''
   let email: string = ''
   let password: string = ''

   let signupError: string = ''
   let formErrors: Record<string, unknown> | undefined
   let loading: boolean = false

   const handleSubmit = async () => {
      signupError = ''
      loading = true
      const values = { name, lastName, email, password }

      formErrors = await validateForm(schema, values)

      if (!formErrors) {
         signup({
            name,
            lastName,
            email,
            password
         }).then((res) => {
            if (res.error) {
               signupError = res.error.graphQLErrors[0].message
            } else {
               signupError = ''
               goto('/')
            }
         })
      }

      loading = false
   }
</script>

<div class="max-w-md mx-auto my-6 bg-slate-200 p-4 lg:p-6 rounded-lg shadow-md">
   <h1 class="underline decoration-blue-500">Регистрация</h1>

   <form on:submit|preventDefault={handleSubmit} class="flex flex-col space-y-3">
      <label>
         <span>Имя</span>
         <input name="name" bind:value={name} />
         {#if formErrors?.name}
            <p class="error">{formErrors.name}</p>
         {/if}
      </label>
      <label>
         <span>Фамилия</span>
         <input name="lastName" bind:value={lastName} />
         {#if formErrors?.lastName}
            <p class="error">{formErrors.lastName}</p>
         {/if}
      </label>
      <label>
         <span>Почта</span>
         <input name="email" type="email" bind:value={email} />
         {#if formErrors?.email}
            <p class="error">{formErrors.email}</p>
         {/if}
      </label>
      <label>
         <span>Пароль</span>
         <input name="password" type="password" bind:value={password} />
         {#if formErrors?.password}
            <p class="error">{formErrors.password}</p>
         {/if}
      </label>

      {#if signupError}
         <p class:error={signupError}>{signupError}</p>
      {/if}

      <button class="btn btn-primary" disabled={loading}>Зарегистрироваться</button>
   </form>

   <p class="text-center underline pt-3">
      <a href="/login">Вход</a>
   </p>
</div>
