// apps/svelte-kit/src/components/Main/Courses.svelte
<script lang="ts">
   import Container from '$ui/Container.svelte'
   import { operationStore, query } from '@urql/svelte'
   import CourseCard from './CourseCard.svelte'
   import {
      GetCoursesDocument,
      type GetCoursesQuery,
      type GetCoursesQueryVariables
   } from '$api/generated'

   const courses = operationStore<GetCoursesQuery, GetCoursesQueryVariables>(GetCoursesDocument, {
      take: 3
   })

   query(courses)
</script>

<Container id="courses">
   <h1 class="text-2xl">Последние курсы</h1>

   {#if $courses.fetching}
      <p>Загрузка...</p>
   {:else if $courses.error}
      <p>{$courses.error.message}</p>
   {:else}
      <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 mt-6">
         {#each $courses.data.courses as course}
            <CourseCard data={course} />
         {/each}
      </div>
   {/if}
</Container>

// apps/frontend-next/components/Main/Courses.tsx
import Container from '@components/utils/Container'
import CourseCard from '../common/CourseCard'
import Button from '@components/utils/Button'
import { useRouter } from 'next/router'
import { useGetCoursesQuery } from '@api/generated'
import { useUser } from '@lib/useUser'
import CourseCardsWrapper from '@components/common/CourseCardsWrapper'

const Courses = () => {
   const { user } = useUser()
   const { data, isLoading, error, isFetching } = useGetCoursesQuery({
      take: 3,
   })

   const router = useRouter()

   return (
      <Container id="courses">
         <h1 className="text-2xl">Последние курсы</h1>

         {isLoading || isFetching ? (
            <p>Загрузка...</p>
         ) : error ? (
            <p>{JSON.stringify(error)}</p>
         ) : (
            <CourseCardsWrapper>
               {data?.courses?.map(course => (
                  <CourseCard data={course} key={course.id} />
               ))}
            </CourseCardsWrapper>
         )}

         {data?.courses && (
            <div className="text-center mt-10">
               <Button
                  theme="light"
                  onClick={() => {
                     router.push('/courses')
                  }}
               >
                  Посмотреть все курсы
               </Button>
            </div>
         )}
      </Container>
   )
}

export default Courses
