// apps/svelte-kit/src/components/Main/Courses.svelte
<script lang="ts">
   import Container from '$ui/Container.svelte'
   import { operationStore, query } from '@urql/svelte'
   import CourseCard from './CourseCard.svelte'
   import {
      GetCoursesDocument,
      type GetCoursesQuery,
      type GetCoursesQueryVariables
   } from '$api/generated'

   const courses = operationStore<GetCoursesQuery, GetCoursesQueryVariables>(GetCoursesDocument, {
      take: 3
   })

   query(courses)
</script>

<Container id="courses">
   <h1 class="text-2xl">Последние курсы</h1>

   {#if $courses.fetching}
      <p>Загрузка...</p>
   {:else if $courses.error}
      <p>{$courses.error.message}</p>
   {:else}
      <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 mt-6">
         {#each $courses.data.courses as course}
            <CourseCard data={course} />
         {/each}
      </div>
   {/if}
</Container>

// apps/frontend-react/src/components/Main/Courses.tsx
import { client } from '@api/client'
import { useGetCoursesQuery } from '@api/generated'
import { SimpleGrid } from '@mantine/core'
import { useNavigate } from 'react-router-dom'
import { Button, Container } from 'ui'
import CourseCard from './CourseCard'

const Courses = () => {
   const navigate = useNavigate()

   const { data, error, isLoading, isFetching } = useGetCoursesQuery(
      {
         take: 3,
      },
      {
         retry: false,
      }
   )

   return (
      <Container id="courses">
         <h1 className="text-2xl">Последние курсы</h1>

         {isLoading ? (
            <p>Загрузка...</p>
         ) : error ? (
            <p>{JSON.stringify(error)}</p>
         ) : (
            <>
               <SimpleGrid
                  breakpoints={[
                     { minWidth: 'xs', cols: 1 },
                     { minWidth: 'md', cols: 2 },
                     { minWidth: 'lg', cols: 3 },
                  ]}
                  className="gap-8 my-6"
               >
                  {data.courses.map(course => (
                     <CourseCard key={course.id} data={course} />
                  ))}
               </SimpleGrid>
               <Button
                  onClick={() => navigate('/courses')}
                  variant="outline"
                  className="mx-auto block"
               >
                  Посмотреть все курсы
               </Button>
            </>
         )}
      </Container>
   )
}

export default Courses
